// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/engine/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{})
}
